name: Run YTAgent

on:
  schedule:
    - cron: '0 8 * * *'   # Every day at 8 AM UTC
    - cron: '0 20 * * *'  # Every day at 8 PM UTC
  workflow_dispatch:       # Manual button trigger

jobs:
  run-container-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull container image
        run: docker pull quay.io/abhaynigam/ytagent

      - name: Run container with explicit command
        id: run_container
        run: |
          CONTAINER_ID=$(docker run -d quay.io/abhaynigam/ytagent bash /app/main.sh)
          echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT

      - name: Wait for container to finish
        run: |
          docker wait ${{ steps.run_container.outputs.container_id }}

      - name: Copy output files from container
        run: |
          docker cp ${{ steps.run_container.outputs.container_id }}:/app/urls.json urls.json
          docker cp ${{ steps.run_container.outputs.container_id }}:/app/currentindex.txt currentindex.txt
          docker rm ${{ steps.run_container.outputs.container_id }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add urls.json currentindex.txt
          git commit -m "Update urls.json and currentindex.txt from container run" || echo "No changes to commit"
          git push origin main
