name: Run YTAgent

on:
  schedule:
    - cron: '0 8 * * *'   # Every day at 8 AM UTC
    - cron: '0 20 * * *'  # Every day at 8 PM UTC
  workflow_dispatch:

jobs:
  run-container-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull container image
        run: docker pull quay.io/abhaynigam/ytagent

      - name: Create container (idle)
        id: create_container
        run: |
          CONTAINER_ID=$(docker create -it quay.io/abhaynigam/ytagent tail -f /dev/null)
          echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT

      - name: Copy currentindex.txt into container before execution
        run: |
          docker cp currentindex.txt ${{ steps.create_container.outputs.container_id }}:/app/currentindex.txt

      - name: Start container
        run: |
          docker start ${{ steps.create_container.outputs.container_id }}

      - name: Run main.sh using bash inside container
        run: |
          docker exec ${{ steps.create_container.outputs.container_id }} bash /app/main.sh

      - name: Copy output files from container
        run: |
          docker cp ${{ steps.create_container.outputs.container_id }}:/app/urls.json urls.json
          docker cp ${{ steps.create_container.outputs.container_id }}:/app/currentindex.txt currentindex.txt

          docker rm -f ${{ steps.create_container.outputs.container_id }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add urls.json currentindex.txt
          git commit -m "Update urls.json and currentindex.txt from container run" || echo "No changes to commit"
          git push origin main
